[package]
name = "example"
version = "0.10.1"
edition = "2021"

[dependencies]
winit = "0.30"
wgpu = "25.0"
futures = "0.3"
bytemuck = { version = "1.16", features = ["derive"] }
encase = { version = "0.11", features = ["glam"] }
# This must match the version supported by encase.
glam = { version = "0.30", features = ["bytemuck"] }
bon = "3.5"
ordered-float = "5.0"

[build-dependencies]
wgsl_to_wgpu = { path = "../wgsl_to_wgpu" }
